### ISSUE TITLE
Min values 1 causing recursion in document type editor

### ISSUE THREAD

**Issue by SayTen** [leekelleher/umbraco-nested-content#100]
I created a nested type with 1 minimum value.  When opening the document type editor it would write out the example node, which would create one node and then include the directive processes with the 1 minimum node, which creates the directive.  That's my understanding of what's happening, setting min value to 0 works around this.

**Comment by seanoldfield** [comment]
I am also having this issue, it's causing the back office to become unresponsive and eventually crash due to an infinite loop

Running version 0.3.0 on Umbraco version 7.5.8

**Comment by leekelleher** [comment]
I'm not sure of the status with this issue, I haven't experienced it myself.

Since we have migrated NC to (upcoming) Umbraco v7.7.0, we are not looking to make any changes to the codebase of the package version of NC.  If the issue persists, then please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
