### ISSUE TITLE
Nested Content requires I press Save+Publish twice

### ISSUE THREAD

**Issue by rocifier** [leekelleher/umbraco-nested-content#106]
When using nested content, the first time I click save, I see the title update on the item I saved - this is persistent. However, on the front-end website, reading the data from the nested content results in the old items. For the new item(s) to show up on the front-end I need to press save+publish a second time.

The content I am nesting is a nupicker (custom type), see below:

[http://i.imgur.com/tuXlBSD.png](url)
[http://i.imgur.com/LE8eVpG.png](url)

**Comment by leekelleher** [comment]
I'm not sure of the status with this issue?

Since we have migrated NC to (upcoming) Umbraco v7.7.0, we are not looking to make any changes to the codebase of the package version of NC.  If the issue persists, then please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
