### ISSUE TITLE
What would it take to get OfType<T>() to work with NC

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-nested-content#118]

**Comment by mattbrailsford** [comment]
This is a ModelsBuilder related question. Looking at the implementation of OfType in core, it just does a simple "is" type check, so the model needs to already be of the given type.

Options could be 1) we support models builder and within the value converter convert the items to the respective types or 2) implement an OfType method of our own that simply create a models builder model for the given type. 

I think option 1 would probably be the correct answer but would mean we'd have a dependency on MB

**Comment by tompipe** [comment]
I've added some ~~crazy~~ magic to all the value resolvers in one of my codebases recently. At it's core, it converts IPublishedContent(s) to strongly typed models, and also returns the type of the matched model from the value converter

Models builder uses that return type the next time models are generated, and it will generate strongly typed properties for all properties returning IPublishedContent(s), including nested content pickers (with a single doctype as the blueprint)

So automatically I get
```C#
///<summary>
/// Team Members
///</summary>
[ImplementPropertyType("teamMembers")]
public IEnumerable<Core.Models.Content.TeamMember> TeamMembers
{
    get { return this.GetPropertyValue<IEnumerable<Core.Models.Content.TeamMember>>("teamMembers"); }
}
```
instead of 
```C#
///<summary>
/// Team Members
///</summary>
[ImplementPropertyType("teamMembers")]
public IEnumerable<IPublishedContent> TeamMembers
{
    get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("teamMembers"); }
}
```
It needs some refactoring and further testing before I share it (maybe as a PR), but in the meantime, this is what handles the model builder conversion

```C#
public IPublishedContent GetTypedModel<TModel>(IPublishedContent nestedContent) where TModel : PublishedContentModel
{
    var factoryResolver = Umbraco.Core.Models.PublishedContent.PublishedContentModelFactoryResolver.Current;
    if (factoryResolver?.HasValue == true)
    {
        return factoryResolver.Factory?.CreateModel(nestedContent) as TModel;
    }

    return nestedContent; // or throw an exception perhaps?
}
```

So I'd vote option 1, given that that factory resolver is in the core anyway. If a factory is configured you can handle the conversion in the value converter, and additionally return the correct strong type, to allow models builder to generate strongly typed nested content properties for free 😄

**Comment by leekelleher** [comment]
Closing this ticket, further details on https://github.com/umco/umbraco-nested-content/pull/124#issuecomment-324618258
