### ISSUE TITLE
DropdownList Multiple is not holding the selected values

### ISSUE THREAD

**Issue by Nikita-reddy** [leekelleher/umbraco-nested-content#12]
I am working with Nested Content, as per my requirement I need to have a dropdown list multiple , based on these values I have to populate the data. But for some reason, my dropdown list multiple in Nested Content is not holding the selected values. Could you please suggest me with regards to this issue.

**Comment by wroughtec** [comment]
The value is not being held for Radio button list either

**Comment by mattbrailsford** [comment]
So, I've managed to find the reason for this.

As part of nested content, when it saves, it get's all nested content property editors and passes the value to store though the property editors `ConvertEditorToDb` function to ensure data stays in an expected format.

Within our version of this method then, we break out the individual values and make that call, with the passed in value cast `.ToString()`. The problem is, the DropdownList multiple (and Radio Button List) are hard coded to expect that value to come in as a `JArray` so because it comes through as a string, it bails and returns null as the value.

Now, the question is, do we make the assumption that all `ConvertEditorToDb` calls should be made passing in the raw value as whatever JSON deserializes it as? or should we make a pull request to make the dropdownlist / radio button controls more forgiving and have them detect a JSON serialized array and convert it.

My problem with the former is that we may find other property editors that may expect things to come through as strings, and then receive `JObject`s or something and thus fail as well.

What do we think the fix should be?

We could as a dirty test have it convert the value twice, onces with string, once with the deserialized value and see if there is a difference, but that seems dirty and wasteful.

**Comment by mattbrailsford** [comment]
PS Supplying the fix to core will obviously come with the caveat that it'll be broken in all version prior to that fix being released.

**Comment by mattbrailsford** [comment]
After speaking with @leekelleher and looking in to it, we are going to go with not calling `.ToString()` on the raw value which should be more like what Umbraco does. I don't believe Umbraco should be relying on a `JArray` being passed in, never the less, this fixes the issue.

**Comment by SergeyIsakovCogniteq** [comment]
This bug still reproduced for 0.2.0.
I added dropdownlist multiple to nested document type. Added nested item to page. And try to get values and get null.

**Comment by leekelleher** [comment]
Hi @SergeyIsakovCogniteq - thanks for raising this. This bug has been fixed since v0.2.0 (released July 2015), we haven't released a new version since... but you can get a copy of the latest v0.3.0-alpha builds from here: https://ci.appveyor.com/project/leekelleher/umbraco-nested-content/build/artifacts

**Comment by leekelleher** [comment]
@SergeyIsakovCogniteq Sorry, ignore my last comment, I got my dates mixed up. :confounded:

**Comment by SergeyIsakovCogniteq** [comment]
Hi @leekelleher , thanks for response, i try v0.3.0-alpha , but its build have next problem - for dropdownlist we get id`s not values, and for checkbox list we have same problem as for 0.2.0.
