### ISSUE TITLE
"Choose type of content" dialog always opens on top of the edit page

### ISSUE THREAD

**Issue by met67** [leekelleher/umbraco-nested-content#130]
I have a document type with several properties, the last being a Nested Content data type with multiple sub types.
In the editing a node I have to scroll down the page to reach the (+) icon and add some content to my NC propery, but the dialog opens at the very top of the page and I have to scroll up to see it and chose the content type.
At first I even thought that NC was not working, since clicking on the (+) icon didn't seem to do nothing!

**Comment by leekelleher** [comment]
@met67 Thanks for reporting... this has been fixed (in PR #123) for the next release, (we haven't set a release date yet).

**Comment by leekelleher** [comment]
@met67 If you need the fix now, then the latest package build is available on NuGet/MyGet:
https://www.myget.org/gallery/umbraco-packages

If you aren't using NuGet, then the Umbraco package zip can be downloaded from the latest AppVeyor build:
https://ci.appveyor.com/project/UMCO/umbraco-nested-content/build/artifacts

**Comment by met67** [comment]
Thanks!

**Comment by zpbd** [comment]
@leekelleher unfortunately I don't think this problem has gone away.

I've tried out [your refactor](https://github.com/umco/umbraco-nested-content/commit/9884999e65fbf9be5c2cd43c14f52a4302d1baec) of [SayTen's PR](https://github.com/umco/umbraco-nested-content/pull/123), and for me this causes the dialog window to appear off the bottom of the tab, pushing the pane down. The user then needs to try to scroll down the page, but loses focus on the dialog whilst doing so. I've attached two screenshots to demonstrate.

For me, the original PR by SayTen is preferable and this is what I am using for now - the dialog is always fixed in the middle of the browser window. It looks odd because obviously it appears "over to the left" of the tab that you are editing, but at least it will always be visible.

```
.usky-grid.nested-content__node-type-picker .cell-tools-menu {
    position: fixed;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
}
```

I think this needs resolving quickly in a release because a lot of people might be trying out Nested Content and just thinking it doesn't work if they add an NC property at the bottom of a long set of fields. Unfortunately I can't think of a satisfactory CSS-only solution. It might be simpler all around if the dialog appears instead as a pane that comes out from the right, this would also keep it consistent with the rest of the backoffice. Just a thought.

![ncissue1](https://user-images.githubusercontent.com/11717300/26874779-c78b094e-4b76-11e7-8490-ff405971089d.png)

![ncissue2](https://user-images.githubusercontent.com/11717300/26874789-d39801e2-4b76-11e7-8c3d-bb0b958837a1.png)

**Comment by leekelleher** [comment]
@zpbd Thanks for your comments, (I'm catching up after CG17).  I've opened a new issue for this, so I will remember to review it, #132.

My issue with the modal being positioned in the middle/centre, is that it looked far too offset when using NC inside a side-panel, (such as DTGE).  I wanted to keep it relative to the NC itself.  I'm totally open to any improvements on this.
