### ISSUE TITLE
Performance - Nested content with RTE

### ISSUE THREAD

**Issue by crixlis** [leekelleher/umbraco-nested-content#136]
Hi,

Thanks for this Umbraco plugin, which is great. I stumbled on an performance issue when I was using the plugin for a webproject. Hope you can help me.

 I was doing the follow:
- I made an nested content doctype with an textstring field and a RTE field.
- I made an item that supports the nested content
- I tried to add items based on the nested content

**Problem:**
When I added an item in the nested content panel I got an problem with using the RTE-functionalities. Clicking on an button in the RTE results in an overlay window, but it loads very slowly. I takes sometimes over 10 seconds. 
![rte_problem](https://user-images.githubusercontent.com/16986981/28308331-2264326a-6ba6-11e7-96c9-d30267f496ce.JPG)
In the project that I’m working on, the hyperlink functionality is important.
Seems there is a workaround by clicking on the div “nested-content__footer-bar”, because it causes the select link window overlay renders. It immediately renders and there is no problem at all...
![rte_problem_workarround](https://user-images.githubusercontent.com/16986981/28308343-2e55c4d0-6ba6-11e7-9a9c-67c7998a3f56.JPG)

But I wonder, am I the only one with this problem / is this something that can be fixed?

Crix

**Comment by crixlis** [comment]
Does anyone know a solution for this problem? If I need to provide more information about the issue, just let me know.

**Comment by leekelleher** [comment]
I'm not sure of the status with this issue? I've not been able to reproduce it myself.

Since we have migrated NC to (upcoming) Umbraco v7.7.0, we are not looking to make any changes to the codebase of the package version of NC.  If the issue persists, then please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).

If it is found to be a bug - and we can apply a fix to the package version of NC, then we can attempt to retrofit it, for backwards compatibility.
