### ISSUE TITLE
Feature Request - Tabbed Interface

### ISSUE THREAD

**Issue by photogsy** [leekelleher/umbraco-nested-content#149]
It would be great if there were some way to group the nested content types in the picker so that users can more easily choose the right item to add.
We have quite a lot of different 'blocks' and it would be great if we could group them into, for example, 'Hero Blocks', 'Image/Text Blocks', 'Text Blocks', etc

It would also be really great if there were some way to show a preview of each item, again, to help users in choosing the right type of content to add.

![image](https://user-images.githubusercontent.com/27409138/41226405-46449af6-6d69-11e8-8a87-0977edf01d2c.png)

**Comment by leekelleher** [comment]
Hi @photogsy - thanks for taking the time to raise a feature request.

Since Nested Content is now part of the Umbraco core distribution, we are no longer maintaining it as a separate package.  Any new feature request will need to be submitted on the [Umbraco issue tracker](http://issues.umbraco.org/).

Thanks!
