### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by lele7** [leekelleher/umbraco-nested-content#16]
No validation for any field. It would be nice to have the validation on the save event.

**Comment by mattbrailsford** [comment]
NC already has mandatory field validation, you should be able to set mandatory fields on your NC doctype properties and it will force them required. We can't handle regex validation, but we handle required.

Is this not the case? Can you provide replication steps?

**Comment by mattbrailsford** [comment]
In fact, I'm wrong, we should handle regex aswell

**Comment by lele7** [comment]
Thanks for your feedback. 
I used it with the grid doc type and the mandatory validation didn't work.

**Comment by mattbrailsford** [comment]
Hi @lele7, I'm not sure what you mean by "the grid doc type". Can you provide as much contextual info as you can so I can try and reproduce?

Many thanks

**Comment by lele7** [comment]
sure I created a nested content type "contact item" with some fields (name, prename, email, and so on) after that I created the contact doc type with the reference on the nested contact items.

Now I added this doc type "contact" to the grid editors config (doc type grid package) something like that:

  {
    "name": "Contact",
    "alias": "Contact",
    "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
    "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
    "icon": "icon-user",
    "config": {
      "allowedDocTypes": [
        "^Contact$"
      ],
      "enablePreview": true,
      "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
      "previewCssFilePath": "",
      "previewJsFilePath": ""
    }
  }

after these steps I allowed the "Contact" doc type in the grid data type.
and at the end I'm wrapped the grid datatype with ur vorto package for the 1:1 translation....

that's it :)

**Comment by lele7** [comment]
but now I have seen that you have a behaviour on the vorto data type settings which is standard on ignore... I think I have to put it on "Any Mandatory"...

I have tested it but it happened no Validation no matter what I set

**Comment by leekelleher** [comment]
To clarify... you have a Vorto property with a Grid inside, using a DocType Grid Editor with a Nested Content? ... and the mandatory validation isn't working?

Honestly, I think it is going to be difficult to support that scenario. I'm struggling to comprehend how the validation error messages would be displayed.

**Comment by lele7** [comment]
Yes that's right.

**Comment by mattbrailsford** [comment]
In that case, I don't think it's going to be possible. The validation built into the nested content property is serverside only and because it's not being used as the main datatype control, it won't run.

Really, the datatype in control of the validation is the Vorto property. This does support mandatory validation, but this would be checking against the grid, which I'm pretty sure does not, so in that instance I doubt it would work.

The only thing that we could try and do is do something in DocTypeGridEditor to try and validate it's innner doc type, but again, this is tricky when there is not standard way of doing validation, so as it stands, it's basically not possible I'm afraid.
