### ISSUE TITLE
Firefox unable to edit text string fields in a nested content

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-nested-content#17]
From the forum...

> I'm having an issue with Firefox where the nested content item's Textstring fields don't allow any focus or editing in the browser. I can use content or media pickers, but the textstrings are un-editable.
> 
> Anyone else experiencing this?
> 
> I can edit in Chrome just fine.

https://our.umbraco.org/projects/backoffice-extensions/nested-content/nested-content-feedback/66853-firefox-unable-to-edit-text-string-fields-in-a-nested-content

**Comment by mattbrailsford** [comment]
Can't seem to replicate this.

Using Firefox v35.0 I've been able to modify text properties inside nested content without problem.

Do we have any additional replication steps? Are there any JS errors present?

**Comment by leekelleher** [comment]
@protherj - do you have any JS errors from Firefox?

**Comment by protherj** [comment]
Sadly no console errors.  I'll try it on some other machines and see if I can replicate it.

Thanks,
Jason

**Comment by kgiszewski** [comment]
This has plagued Archetype: https://github.com/imulus/Archetype/issues/61

Tom Fulton traced it backed to possibly UI.sortable.

**Comment by leekelleher** [comment]
@kgiszewski Thanks for the heads up!

**Comment by mattbrailsford** [comment]
Ok, well, if the Archetype issue is correct, and it's to do with disableSelection() being called, it looks like that should have been fixed since Umbraco 7.2.0 (https://github.com/umbraco/Umbraco-CMS/commit/ef6e181eb1fc61d70884680517ff4de2cfcb34eb). This could be why it's working for me as I'm testing in 7.2.6.

Rather than dotting our code with an ugly fix then, my suggestion would be to upgrade to at least 7.2.0.

Thanks for the heads up @kgiszewski, that would have been a nightmare to find.

**Comment by protherj** [comment]
Ah yes, this is a 7.1.x site.  I'll get an upgrade on the Backlog and verify that is the fix.

Thanks,
Jason
