### ISSUE TITLE
Label Templates for complex data types (nupicker, contentpicker, dropdown list and so on)

### ISSUE THREAD

**Issue by LeoSchleicher** [leekelleher/umbraco-nested-content#41]
It can be very handful to have possibility in custom label templates by fields with complex type parse them to get applicable values. For example, Nupicker prefetch list picker stores values as something like [{key:"1234"},{label:"nanana"}]. Is it possible to have callback function in template? It seems like Archetype has something alike.

**Comment by mattbrailsford** [comment]
I've not tried, but I wonder if {{prop[0].label}} would work as a nameTemplate? If it doesn't I'd be ok with making something like I've presented work, however allowing functions to be supplied would be something I'd discourage.

**Comment by LeoSchleicher** [comment]
I'm tried, this not working. prop[0] returns first char of json string. in my case "["

**Comment by mattbrailsford** [comment]
then I think we can add something to detect a json strong and convert it to a javascript object before running the nameTemplate.

**Comment by ksolberg** [comment]
It would be really useful if you could support fetching a target node name based on an id in the label syntax. F.ex. {{ someContentPickerProp.Name() }}

**Comment by d-schloss-mvg** [comment]
Add these lines:

for (var f in $scope.model.value[idx]) {
    var v = $scope.model.value[idx][f];
    try {
        v = angular.fromJson(v);
        $scope.model.value[idx][f] = v;
    } catch (e) { };
}

just before 
var newName = contentType.nameExp($scope.model.value[idx]);

in nestedcontent.controllers.js

But this is actual only for version 0.2. Development version from git has additions and probably will not work.
After that you can use nuPickers with stored json values

**Comment by mattbrailsford** [comment]
The main problem I have with this is that you would need to run all the data through their respective property editors value converters in order to retrieve a "known" data format, so anything other than this that we add would be a bit of a cludge. You can already access data from within complex property editors, if you know how they store their data in the angular model so if you want to do that, you can, but it's probably not a recommended approach as the editor data is not guaranteed to be the final value presented on the front end and really should be considered internal to the property editor and liable to changes (changes in the PE model would not be classed as breaking changes).

Ultimately I don't think the payout is worth the effort / processing it would take to do this, but if anyone wants to take a look and submit a PR, I'd be happy to review it.

**Comment by Myster** [comment]
There are so many things people could display in the 'label' area, I would like to be able to supply a function which will return arbitrary markup, this way I can do various things like:
- Take the first line from an RTE
- Show a thumbnail of a picked media item
- Show the name of a picked node (that's a popular one)
- Show a list of titles/thumbnails picked via a multipicker (media or content)
- etc...

**Comment by leekelleher** [comment]
Closing this one off, as there is a longer discussion on the same topic in issue #63
