### ISSUE TITLE
UI gets hidden at certain resolutions

### ISSUE THREAD

**Issue by AussieInSeattle** [leekelleher/umbraco-nested-content#5]
Can't upload a screenshot due to doc type having sensitive content, but at a browser width of <~1210px down to ~1118px (when the left tree disappears) the nested items are being obscured and there is no horizontal scrollbar.  The nest content type has two textstrings and a textarea (textstring multiple).

Same (less of an issue) with anything <~850px wide which makes it not tablet friendly (I think?).

It's nice that you can hide the label but then I also lose the helptext for the "parent property".  Maybe have an option to stack the nested property under the label+helptext - understand that could make things a little cluttered though.

Awesome work.

**Comment by mattbrailsford** [comment]
This should now be fixed in this commits 3863abf5498a5eea4b436dcb27e128232b210326 and 7f5cc0630ff2239577f88fd21e88efbf9d03bf60 I've made it so that within a nested content control, the umbraco property is now set to use percentages for it's layout, rather than fixed pixel widths.

You might still get some overlap with any control that has a specific width set on them, but that's really an issue with the control.
