### ISSUE TITLE
Bug when using Nested Content with Repeatable Textstrings.

### ISSUE THREAD

**Issue by allanlange** [leekelleher/umbraco-nested-content#58]
Hi Lee,

I have found what I believe to be a bug in your package. The bug is in regards to Repeatable Textstrings. When using Repeatable Textstrings in Nested Content, it outputs line breaks as empty strings.

I had originally posted the issue on "Our" (https://our.umbraco.org/forum/using-umbraco-and-getting-started/76559-repeatable-textstrings-outputs-empty-strings).

Regards,

Allan @ Ecreo Denmark

**Comment by leekelleher** [comment]
@allanlange Thanks for raising this, we'll take a look, (but also marked it as "up-for-grabs", if a community member wants to pick it up sooner).

**Comment by leekelleher** [comment]
Progress update on this issue.  I spent a few hours digging around the Umbraco core codebase to figure out what was happening with the Repeatable Textstring values.

It turns out that when you use a Repeatable Textstring (also know as Multiple Textstring within the core code) as a regular property, the value it saves to the database (and XML cache) delimits the values with a `Environment.NewLine` (e.g. `"\r\n"`). However once the content is edited, the values become delimited with a Unix-type newline (e.g. `"\n"`), which is what the Umbraco core converter is expecting.

> See [line 55 in `MultipleTextStringValueConverter`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/PropertyEditors/ValueConverters/MultipleTextStringValueConverter.cs#L55) to prove this.

The `sourceString.Split(Environment.NewLine.ToCharArray())` line will split the string by `'\r'`, then by `'\n'`.

This means that after an initial save of a content node, the a Repeatable Textstring property will be processed by the converter with `"\r\n"` delimiter and give extra blank items.  Then once the content node is re-saved it will have a `"\n"` delimiter and be processed as expected.

Now for Nested Content... since the overall value we store in both the database and XML cache is a JSON blob/string, the value delimiter for a nested Repeatable Textstring is never modified, it always remains as `"\r\n"`, which is why you will always get the extra blank items returned by the converter.

This is a bug within the Umbraco core, which would mean the converter needs to be modified to handle both `"\r\n"` and `"\n"` delimiters.

**Comment by leekelleher** [comment]
I've raised a bug on the Umbraco issue tracker: http://issues.umbraco.org/issue/U4-8712

Closing this issue, as requires a fix in Umbraco core.
