### ISSUE TITLE
Label template niceness

### ISSUE THREAD

**Issue by greystate** [leekelleher/umbraco-nested-content#63]
It would be great to be able to specify a fallback for the label when the label template resolves to an empty (or whitespace-only) string.

(Or I may not be sufficiently Angular-skilled to have figured it out yet :-)

**Comment by mattbrailsford** [comment]
It should fallback to "item 1, item 2, item 3" etc if it's empty. It's just tricky providing a way to do fancy labels as it's how we allow the logic to be defined. Maybe we can look at allowing developers to provide either a link to an angular include, or some angular markup to render as the label?

**Comment by greystate** [comment]
Yeah, the "Item 1", "Item 2" labels are probably the real issue. Would be so much nicer to be able to have them be meaningful with regards to the specific datatype, instead of overly generic as they currently are :)

**Comment by Myster** [comment]
I advocate going a step further and allowing a function to be specified to generate the label ( as per issue #41 ) or some other way which is just as flexible.

**Comment by mattbrailsford** [comment]
The problem is, there is no nice way to go about this. Take Archetype for example https://github.com/kgiszewski/ArchetypeManual/blob/master/02%20-%20Configuration.md#label-template, they allow custom functions for labels, but it's just really cumbersome to implement IMO (For the record, I can't think of an alternative way, so what they have come up with is probably what I would have implemented). 

First you need to create a js file, then include it via the package manifest (or I think they have a prevalue config option too), then you need to define your function accepting specific arguments (I guarantee someone will always want access to something not defined), and then you have to setup the label template. In addition, the likelihood is you are going to need to make HTTP requests to a web service to get the label names from some back office implementation which may also need building by yourself, then finally, the label templates are processed every time an item changes so you'll be potentially making a bunch of web requests all to get a label, when adding a simple "label" field on your NC doc type would circumvent all of this, but just require your users to name things.

I understand that this would be the problem of the developer wanting to create the label, but I just feel it'll open a heap of maintenance issues.

Given @greystate's comments saying it's more the "item 1, item 2, item 3" that is the issue for him, the only thing I can think to go is maybe expose the current index as a template parameter so you could define a label like "Item {index}" where you know it's going to be tricky to dynamically formulate a label?

I'm open to suggestions / PR's for ways to do this in a nicer way though.

**Comment by Myster** [comment]
I was envisaging having to do all those steps you described (at least for more complex scenarios),  but frankly probably the only scenario I'd bother with is taking the first line from an RTE. (and perhaps looking up node names)

**Comment by Myster** [comment]
Also just discovered I'd like to put HTML markup in the label, Currently I'm just thinking `<strong>` but I imagine more complex layout may be useful too.

**Comment by mattbrailsford** [comment]
Just had an interesting discussion on twitter with someone who is trying to run a filter in a labelTemplate and whilst his doesn't work currently (because the value isn't in the right format for the filter) filters do actually run, so we actually have a way of running functions in label templates by making angular filters.

So, you could make a filter to fetch a node name, then in your label template, have something like {{mediaPicker|nodeName}} and the filter will process the id and do something with it. This in theory allows you to run custom code within your labels without us needing to support extra weirdness.

I still think we probably need a way to expose the index of the current item, but I'm pretty happy to call this a solution for any, more complex, label generation.

**Comment by Myster** [comment]
Sounds great, I'll have to give it a whirl :-)

**Comment by leekelleher** [comment]
@mattbrailsford I tried out a test filter, it gets called a LOT, as in at least 15 times on initial page load, then whenever angular tries to rebind the model. Just moving my mouse around made at least another 20 calls to the filter. Not sure if there's a way to prevent (or pause) the aggressive rebinding?

(Ignore until next week :sunglasses::surfer::ocean::cocktail::sunrise:)

**Comment by yoerivdm** [comment]
Maybe a very noobish remark ... just started using nested content and have no angular knowledge (for now)...

Wouldn't it be possible to bind the 'Item x' label to the value of the first inputfield underneath it? That's what I would want to see ...

**Comment by Myster** [comment]
Perhaps one could add a 'cooldown' guard condition to each filter? (bit naff, but should work)

**Comment by YodasMyDad** [comment]
@leekelleher did you ever come up with a solution for the filter getting called a ton of times?

**Comment by leekelleher** [comment]
@YodasMyDad Nope, I gave up on it, my Angular knowledge isn't that great 😔

**Comment by dryton** [comment]
It'd be great if it could convert content IDs to names for usability.

I had a play around with the script and saw the same issue with the getName function being called a whole load of times. Making a call off to fetch the name would be a real performance hit as it stands.

**Comment by mattbrailsford** [comment]
Man, didn't realize implementing a local cache was that hard ;)

https://gist.github.com/mattbrailsford/d7f512ca4a6f24ebe70ebed82eb163f5

**Comment by hfloyd** [comment]
Hi @mattbrailsford , Did you close this because it is/will be included in a release, or because it will not be included? Just checking since the code link is a gist and not a PR....

**Comment by leekelleher** [comment]
It is included in the latest release, v0.4.0.

**Comment by hfloyd** [comment]
Fantastic! Thanks for the info, @leekelleher

**Comment by CostinTanasoiu** [comment]
Could this feature go into the Developer's Guide document?
