### ISSUE TITLE
MNTP +Add disapears after expanding nested item multiple times.

### ISSUE THREAD

**Issue by Myster** [leekelleher/umbraco-nested-content#70]
Given you have an MNTP in a nested item.
Given you have previously selected one or more items in the MNTP.
When you open then close then open that nested item...
Then the `+Add` disappears, and you cannot add more items to the MNTP

**Comment by leekelleher** [comment]
@Myster Thanks for raising this, I've only just had chance to test it out.  I'm surprised that no one else has raised this before.

Also, if you have the "Open" or "Edit" options enabled, those disappear too.

Just curious, did you look into this in any detail? Any ideas why it might be happening?

// Assigning to @mattbrailsford for review, (once back from holiday), as I'm not sure what is happening on the angular side of things.

**Comment by Myster** [comment]
I have not looked into it sorry, I had actually forgotten about it :-], it's only come up once since I found the issue, and I just reloaded the page.

**Comment by felipecruz91** [comment]
I came across the same issue and I wanted to at least give a bit of more information about it:

In the `contentpicker.html` file we have:

` 

```
      <ul class="unstyled list-icons" ng-show="model.config.multiPicker === true || renderModel.length === 0">

        <li>

            <i class="icon icon-add blue"></i>
            <a href="#" ng-click="openContentPicker()" prevent-default>
                <localize key="general_add">Add</localize>
            </a>

        </li>

    </ul>
```

`

So the two conditions that are evaluated in order to show/hide the `+ Add` button are:

`ng-show="model.config.multiPicker === true || renderModel.length === 0"` (line 24)

So, for some unknown reason when you open and close the NestedContent item the value of `model.config.multiPicker` is set to `false` and it never sets back to `true`.
