### ISSUE TITLE
Arabic time when use nested content

### ISSUE THREAD

**Issue by salkhwlani** [leekelleher/umbraco-nested-content#95]
hi,

I changed language of backend to "Arabic" then all nested content not work return this error 

"Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive.
Parameter name: time"

![screen shot 2016-11-02 at 3 05 05 pm](https://cloud.githubusercontent.com/assets/10876587/19928051/d58e57d0-a10d-11e6-9398-62539aa4954c.png)

error happened when call this request 

http://site.com/umbraco/backoffice/UmbracoApi/Content/GetEmpty?contentTypeAlias={alias-nested-content}&parentId=-20

by default 
- Arabic use "UmAlQura Calendar"
- English use "Gregorian Calendar"

i hope you have solution , beacuse umbraco work fine with UmAlQura Calendar except with nested content 

thanks

**Comment by leekelleher** [comment]
@yemenifree Thanks for raising this.  Can you tell us more about your NestedContent configuration, as I don't see any reference to NestedContent code in the error messages.

**Comment by salkhwlani** [comment]
@leekelleher thanks for response , 

I created "Document Types" include two TextString Property then Created "Data Type" 

![screenshot-2016-11-02-15-41-28](https://cloud.githubusercontent.com/assets/10876587/19929190/297461c8-a113-11e6-8c14-e5d1ad1f9c82.png)

i don't know if the problem form Umbraco or NestedContent, but all others Data Type work fine except NestedContent

**Comment by leekelleher** [comment]
@yemenifree Thanks for the update. Since the original error you posted mentioned about date-time. I was  curious if you had a date picker on the NestedContent?

My feeling is that this is an Umbraco issue. But is does seem strange that it's throwing an error when NestedContent is used.  Are there any other date-time pickers on your doctype for that page?

**Comment by salkhwlani** [comment]
i don't use date picker, I think is default Created time of Document type

**Comment by jamiepollock** [comment]
@yemenifree @leekelleher hey chaps, I've been able to recreate this issue but not reliably. At first I was getting issues in both adding a Nested Content data type to a property and also creating new pages with that property.

However after some time, not sure what happened, this problem alleviated. I switched over my current user's culture to make sure it wasn't because it was created a certain way.

Sadly I did get @yemenifree's stack trace but it seems to work fine now. :/ sorry, I can't be of more use. I was wondering if it was because of the current culture's calendar as Gregorian and UmAlQura Calendar min dates differ greatly.

UmAlQura Calendar: 30/04/1900
Gregorian Calendar: 01/01/0001

**Comment by leekelleher** [comment]
I'm not sure what the status of this issue was?

However we have to close this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If this issue still persists in the Umbraco core version of NC, then please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).
